version: "3"
services:
  spring-devops:
    image: kadem_projet
    restart: on-failure
    ports:
      - "8089:8089"
    networks:
      - devops
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysqldb/projDevOps
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
    depends_on:
      - mysqldb

  mysqldb:
    image: mysql:latest
    restart: always
    ports:
      - "3306:3306"
    volumes:
      -  /home/mysql/data:/var/lib/mysql:rw
    networks:
      - devops
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=projDevOps

networks:
  devops:
