version: '3'
services:
  spring-kaddem:
    image: rihabhamoudi/backend
    ports:
      - '8089:8089'
    networks:
      - kaddem
    depends_on:
      - mysql
    volumes:
      - .m2:/root/.m2
  mysql:
    image: mysql:latest
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: devops
      MYSQL_USER: root
      MYSQL_PASSWORD: root
    networks:
      - mynetwork
    volumes:
      - mysql-data:/var/lib/mysql

networks:
  mynetwork:
  kaddem:

volumes:
  mysql-data:
  .m2:
