version: "3"
services:
  spring-kaddem:
    image: rakizouari/kaddem_image
    ports:
      - "8089:8089"
    networks:
      - kaddem-app_default
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysqldb/projDevOps
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD:
    depends_on:
      - mysqldb

  mysqldb:
    image: mysql:8
    volumes:
      -  /home/mysql/ahmeddata:/var/lib/mysql:rw
    networks:
      - kaddem-app_default
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=projDevOps

networks:
  kaddem-app_default: