version: '3'
services:
  kaddem:
    image: ismailkhlif-5se1-g6-kaddem:latest
    restart: on-failure
    ports:
      - '8089:8089'
    depends_on:
      - mysql
    networks:
      - mynetwork
    volumes:
      - .m2:/root/.m2
  mysql:
    image: mysql:latest
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: ismail
      MYSQL_DATABASE: projDevOps
      MYSQL_USER: ismail
      MYSQL_PASSWORD: ismail
    networks:
      - mynetwork
    volumes:
      - mysql-data:/var/lib/mysql
  angular:
    image: docker.io/ismailkhliff/ismail-angular:1.0
    restart: on-failure
    ports:
      - '4222:4222'
    depends_on:
      - kaddem
    networks:
      - mynetwork

networks:
  mynetwork:
    driver: bridge

volumes:
  mysql-data:
  .m2:
